# Site settings
title: Natalia Garcia
description: A blog about my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Natalia Garcia
user_description: Computational Biologist enthusiastic in coding and learning ML and semantic technology applications in Health and biology
user_title: Bioinformatician and Full-stack Data Scientist
email: natalia.garcia.sanchezbc@gmail.com
twitter_username: unknown
github_username:  Natpod
gplus_username:  unknown

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
